id: A3464A60A
title: Prayer for the Long Life of Gyaltön Choktrul Incorporating His Series of Rebirths
type: translation
pechas:
- I7F4E4194
- IE68418EE
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:59:12.189146
  last_modified_at: 2023-01-04 11:59:12.189169
  collections:
  - Gyaltön Rinpoche
  - Works of Tibetan Masters
alignment_to_base:
  I7F4E4194/925F: E210
  IE68418EE/2A98: E210
